#!/bin/bash

#ionic cordova plugin rm cordova-plugin-console

ionic cordova build --release android

#keytool -genkey -v -keystore my-release-key.keystore -alias alias_name -keyalg RSA -keysize 2048 -validity 10000

jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore my-release-key.keystore platforms/android/app/build/outputs/apk/release/app-release-unsigned.apk alias_name

./zipalign -v 4 platforms/android/app/build/outputs/apk/release/app-release-unsigned.apk StorageForage.apk
